### ISSUE TITLE
Add error catching for if no nodes are available

### ISSUE THREAD

**Issue by danspratling** [danspratling/gatsby-source-multi-api#1]
I haven't tested this yet but i'm expecting it to error if no nodes are found on build (ie if the source is empty OR the returned dataset is empty

Todo:
- [ ]  Check what happens when the source is used with an empty array for 'endpoints' and fix any errors which occur
- [ ] Check what happens when the source is used with a api which returns an empty object and fix any errors which occur
- [ ] Check what happens when the source is used with an api which returns an empty array and fix any errors which occur.

Ideally, this would error if there are no endpoints given, but not error if the endpoint is empty (as an empty object/array may be a valid response).

**Comment by ethaneisenhard** [comment]
I love this source plugin, but i think that the code is changing the ID of the data coming in if you use this line 

`const nodeId = createNodeId(`rest-api-result-${result.id}`)`

which makes it hard to run a PUT HTTP request back to the data endpoint if you want to update it, I think you might want to remove that line or make it optional

I am trying to see if I can use the code you wrote and just remove that part but I am not sure how I can do that in my own project, any help would be greatly appreciated.

**Comment by danspratling** [comment]
- [x] When the api option is completely empty, it is skipped
- [x] When the api option is a string, it must have a length or it is skipped
- [x] When the api option is an object, it must contain a `baseUrl` or it is skipped
