### ISSUE TITLE
BUG: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by alexfornuto** [danspratling/gatsby-source-multi-api#10]
First off, I'm loving the changes you made in 1.0.1. Unfortunately it's throwing the following error on `gtabsy develop`:

```
 ERROR #11321  PLUGIN

"gatsby-source-multi-api" threw an error while running the sourceNodes lifecycle:

Cannot read property 'forEach' of undefined

  68 |   };
  69 | 
> 70 |   apis.forEach(api => {
     |        ^
  71 |     /* check if the api request is an object with parameters */
  72 |     if (typeof api === 'object') {
  73 |       const {

File: node_modules/gatsby-source-multi-api/gatsby-node.js:70:8



  TypeError: Cannot read property 'forEach' of undefined
  
  - gatsby-node.js:70 Object.exports.sourceNodes
    [gatsby]/[gatsby-source-multi-api]/gatsby-node.js:70:8
  
  - api-runner-node.js:247 runAPI
    [gatsby]/[gatsby]/dist/utils/api-runner-node.js:247:41
  
  - api-runner-node.js:387 resolve
    [gatsby]/[gatsby]/dist/utils/api-runner-node.js:387:13
  
  - new Promise
  
  - api-runner-node.js:386 runPlugin
    [gatsby]/[gatsby]/dist/utils/api-runner-node.js:386:10
  
  - api-runner-node.js:340 module.exports
    [gatsby]/[gatsby]/dist/utils/api-runner-node.js:340:24
```

I have the plugin defined in `gatsby-config.js` as:

```
  plugins: [
    {
      resolve: `gatsby-source-multi-api`,
      options: {
        urls: [
          {
            prefix: `WordPressAPI`,
            baseUrl: `https://demo.wp-api.org/wp-json/wp/v2/`,
            endpoints: [`posts`, `pages`, `media`, ],
            method: `OPTIONS`,
          },
        ],
      },
    },

...
```

Gatsby will still build, but there are no new nodes in Graphiql.

I took a look at the source code, but as I've mentioned before I'm far from being a Node dev.

**Comment by alexfornuto** [comment]
I've been doing some testing. Logging `apis` was showing it as undefined _until_ I removed the `{}` around it:

```
const apis = configOptions
  console.log("apis values: ", apis )
```

```
apis values:  { plugins: [],
  urls:
   [ { prefix: 'WordPressAPI',
       baseUrl: 'https://demo.wp-api.org/wp-json/wp/v2/',
       endpoints: [Array],
       method: 'OPTIONS' } ] }
```

Now that apis is defined, the issue is with the forEach:

```
 ERROR #11321  PLUGIN

"gatsby-source-multi-api" threw an error while running the sourceNodes lifecycle:

apis.forEach is not a function

  70 |   };
  71 | 
> 72 |   apis.forEach(api => {
     |        ^
  73 |     /* check if the api request is an object with parameters */
  74 |     if (typeof api === 'object') {
  75 |       const {
```

~I'll continue to tinker.~ GOT IT - patch incoming.

**Comment by danspratling** [comment]
This is a complete brainfart on my part. The old key for the array was "urls". during the upgrade i changed this to read "apis" because it's more clear what's expected in that case as the following isn't a url, it's an object with a url _and other things_.

```
{
  baseUrl: "https://some.api",
  endpoints: ["endpoint1", "endpoint2:]
}
```

However i completely missed this when updating the documentation. Thanks for the PR! This would fix the error, but it's much less effort to change the docs than it is to change the code - plus i updated the name in the code for a good reason.

Could you try using the source plugin with the newly corrected documentation and let me know how that works?

**Comment by alexfornuto** [comment]
Yup! Good documentation saves the day once more. At least I learned a bit more about JS in the process. Thanks again!
