### ISSUE TITLE
Q: is the data cached?

### ISSUE THREAD

**Issue by nojaf** [danspratling/gatsby-source-multi-api#12]
Hello @danspratling , I've been able to use this plugin successfully and kudos for this nice plugin!
I was wondering if the data is cached once I run `gatsby develop`? Can I re-fetch the data somehow if I know newer data is available?

**Comment by danspratling** [comment]
It runs as a build process so it won't get new data until you run "gatsby build" again. This is usually fairly reliable (it's the same for any gatsby source plugin) but you can force it to clear by using `gatsby clean` beforehand.

If you want to constantly watch for new data you'll have to use an observable, which this plugin won't be able to help with.

**Comment by nojaf** [comment]
Ok, thanks for clearing that up.
