### ISSUE TITLE
Feature Request: Request Type Option

### ISSUE THREAD

**Issue by alexfornuto** [danspratling/gatsby-source-multi-api#6]
## Summary

I'd like to be able to set the `OPTIONS` method for one or all of my endpoints. 

## Example

Right now I'm experimenting with using `gatsby-source-rest-api` to pull options from the WordPress Rest API to document. As discussed in #5, I have to GET the root call in order to list all the different calls and options available, but that's a huge data set.

If I `curl -X OPTIONS` a specific call, I can get a smaller data set of the options provided by that call. It would be swell if i could specify the `OPTIONS` request for an endpoint provided to the plugin, with `GET` being the default if another request isn't specified.

Thanks for this plugin!

**Comment by danspratling** [comment]
@alexfornuto I'm not super familiar with curl. Could you explain to me what options does? Or send me some documentation for it?

I'm assuming you want to be able to specify routes within an endpoint. So in the case of your wordpress endpoint this would be something like

```
{
  'url': 'https://mysite.com/wp-json',
  'routes': ['pages', 'posts/1', 'users/alexfornuto'] 
}
```

which would give you the following in GraphQL

```
RestApiPages
RestApiPosts1
RestApiUsersAlexfortuno
```

You probably wouldn't request single posts like this, as graphql handles that pretty well - but there's nothing saying you couldn't do that either.

Note i'm not saying this is the right answer to your question - just trying to work out what you're asking.

**Comment by alexfornuto** [comment]
`OPTIONS` is a request type you can submit over HTTP(S). I assume your plugin is hardcoded to use a `GET`, but some APIs, like [WordPress's](https://developer.wordpress.org/rest-api/reference/#a-distributed-api) provide different information for different requests:

> The API also exposes self-documentation at the index endpoint, or via an OPTIONS request to any endpoint, allowing human- or machine-discovery of endpoint capabilities.

The routes option isn't what I'm talking about here, but it's definitely good to know, and IMHO should be added to the README/plugin page.

**Comment by alexfornuto** [comment]
So I did a little browsing in the code. You're `fetch`ing the contents [here](https://github.com/danspratling/gatsby-source-rest-api/blob/master/src/gatsby-node.js#L43) - In the empty second argument, I'm asking for the option to provide another request method, as defined [here](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch):

![image](https://user-images.githubusercontent.com/2349184/74781816-db258600-5267-11ea-9501-ea963d74a926.png)

Specifically, the `OPTIONS` method, for reasons listed above.

**Comment by danspratling** [comment]
I see! I just plugged it into postman and it makes more sense. I'm going to build this plugin out so I can add this amongst other features. I've created a list of things i can think of (and once ticked off i think this might finally reach v1).

@alexfornuto Feel free to look at #7 and add your opinions. I'll be looking at it over the next weekend so anything before then would be extra useful.

**Comment by danspratling** [comment]
This has now been implemented as of `rc1.0.0`. I'm planning on upgrading the project this week which will cause some breaking changes but hopefully be substantially better as a result.

**Comment by danspratling** [comment]
Deployed.
